"""Curated ski resort database - Ikon & Epic Pass North America."""

from app.models import Resort

# Complete list of Ikon and Epic pass resorts in North America
# Organized by state/province for easier maintenance

RESORTS: list[Resort] = [
    # =========================================================================
    # COLORADO
    # =========================================================================
    Resort(
        slug="vail",
        name="Vail",
        state="CO",
        country="US",
        lat=39.6403,
        lon=-106.3742,
        base_elevation_m=2476,
        summit_elevation_m=3527,
    ),
    Resort(
        slug="beaver-creek",
        name="Beaver Creek",
        state="CO",
        country="US",
        lat=39.6042,
        lon=-106.5165,
        base_elevation_m=2469,
        summit_elevation_m=3488,
    ),
    Resort(
        slug="breckenridge",
        name="Breckenridge",
        state="CO",
        country="US",
        lat=39.4817,
        lon=-106.0384,
        base_elevation_m=2926,
        summit_elevation_m=3914,
    ),
    Resort(
        slug="keystone",
        name="Keystone",
        state="CO",
        country="US",
        lat=39.6069,
        lon=-105.9500,
        base_elevation_m=2835,
        summit_elevation_m=3782,
    ),
    Resort(
        slug="crested-butte",
        name="Crested Butte",
        state="CO",
        country="US",
        lat=38.8991,
        lon=-106.9658,
        base_elevation_m=2858,
        summit_elevation_m=3709,
    ),
    Resort(
        slug="aspen-mountain",
        name="Aspen Mountain",
        state="CO",
        country="US",
        lat=39.1875,
        lon=-106.8186,
        base_elevation_m=2422,
        summit_elevation_m=3418,
    ),
    Resort(
        slug="aspen-highlands",
        name="Aspen Highlands",
        state="CO",
        country="US",
        lat=39.1822,
        lon=-106.8556,
        base_elevation_m=2451,
        summit_elevation_m=3559,
    ),
    Resort(
        slug="buttermilk",
        name="Buttermilk",
        state="CO",
        country="US",
        lat=39.2069,
        lon=-106.8681,
        base_elevation_m=2399,
        summit_elevation_m=3018,
    ),
    Resort(
        slug="snowmass",
        name="Snowmass",
        state="CO",
        country="US",
        lat=39.2130,
        lon=-106.9378,
        base_elevation_m=2473,
        summit_elevation_m=3813,
    ),
    Resort(
        slug="steamboat",
        name="Steamboat",
        state="CO",
        country="US",
        lat=40.4572,
        lon=-106.8045,
        base_elevation_m=2103,
        summit_elevation_m=3221,
    ),
    Resort(
        slug="winter-park",
        name="Winter Park",
        state="CO",
        country="US",
        lat=39.8841,
        lon=-105.7627,
        base_elevation_m=2743,
        summit_elevation_m=3676,
    ),
    Resort(
        slug="copper-mountain",
        name="Copper Mountain",
        state="CO",
        country="US",
        lat=39.5022,
        lon=-106.1497,
        base_elevation_m=2926,
        summit_elevation_m=3753,
    ),
    Resort(
        slug="eldora",
        name="Eldora",
        state="CO",
        country="US",
        lat=39.9372,
        lon=-105.5828,
        base_elevation_m=2859,
        summit_elevation_m=3273,
    ),
    Resort(
        slug="arapahoe-basin",
        name="Arapahoe Basin",
        state="CO",
        country="US",
        lat=39.6425,
        lon=-105.8719,
        base_elevation_m=3286,
        summit_elevation_m=3978,
    ),
    Resort(
        slug="telluride",
        name="Telluride",
        state="CO",
        country="US",
        lat=37.9375,
        lon=-107.8123,
        base_elevation_m=2659,
        summit_elevation_m=4010,
    ),
    Resort(
        slug="loveland",
        name="Loveland",
        state="CO",
        country="US",
        lat=39.6800,
        lon=-105.8978,
        base_elevation_m=3230,
        summit_elevation_m=3871,
    ),
    # =========================================================================
    # UTAH
    # =========================================================================
    Resort(
        slug="park-city",
        name="Park City",
        state="UT",
        country="US",
        lat=40.6514,
        lon=-111.5080,
        base_elevation_m=2103,
        summit_elevation_m=3048,
    ),
    Resort(
        slug="deer-valley",
        name="Deer Valley",
        state="UT",
        country="US",
        lat=40.6375,
        lon=-111.4783,
        base_elevation_m=2003,
        summit_elevation_m=2917,
    ),
    Resort(
        slug="alta",
        name="Alta",
        state="UT",
        country="US",
        lat=40.5884,
        lon=-111.6387,
        base_elevation_m=2600,
        summit_elevation_m=3216,
    ),
    Resort(
        slug="snowbird",
        name="Snowbird",
        state="UT",
        country="US",
        lat=40.5830,
        lon=-111.6538,
        base_elevation_m=2365,
        summit_elevation_m=3353,
    ),
    Resort(
        slug="brighton",
        name="Brighton",
        state="UT",
        country="US",
        lat=40.5980,
        lon=-111.5833,
        base_elevation_m=2669,
        summit_elevation_m=3231,
    ),
    Resort(
        slug="solitude",
        name="Solitude",
        state="UT",
        country="US",
        lat=40.6199,
        lon=-111.5919,
        base_elevation_m=2439,
        summit_elevation_m=3048,
    ),
    Resort(
        slug="snowbasin",
        name="Snowbasin",
        state="UT",
        country="US",
        lat=41.2160,
        lon=-111.8569,
        base_elevation_m=1925,
        summit_elevation_m=2896,
    ),
    Resort(
        slug="powder-mountain",
        name="Powder Mountain",
        state="UT",
        country="US",
        lat=41.3789,
        lon=-111.7808,
        base_elevation_m=2011,
        summit_elevation_m=2758,
    ),
    # =========================================================================
    # CALIFORNIA
    # =========================================================================
    Resort(
        slug="mammoth-mountain",
        name="Mammoth Mountain",
        state="CA",
        country="US",
        lat=37.6308,
        lon=-119.0326,
        base_elevation_m=2424,
        summit_elevation_m=3369,
    ),
    Resort(
        slug="june-mountain",
        name="June Mountain",
        state="CA",
        country="US",
        lat=37.7672,
        lon=-119.0894,
        base_elevation_m=2545,
        summit_elevation_m=3098,
    ),
    Resort(
        slug="palisades-tahoe",
        name="Palisades Tahoe",
        state="CA",
        country="US",
        lat=39.1969,
        lon=-120.2358,
        base_elevation_m=1890,
        summit_elevation_m=2760,
    ),
    Resort(
        slug="heavenly",
        name="Heavenly",
        state="CA",
        country="US",
        lat=38.9353,
        lon=-119.9400,
        base_elevation_m=1995,
        summit_elevation_m=3060,
    ),
    Resort(
        slug="northstar",
        name="Northstar",
        state="CA",
        country="US",
        lat=39.2746,
        lon=-120.1210,
        base_elevation_m=1929,
        summit_elevation_m=2624,
    ),
    Resort(
        slug="kirkwood",
        name="Kirkwood",
        state="CA",
        country="US",
        lat=38.6850,
        lon=-120.0653,
        base_elevation_m=2377,
        summit_elevation_m=2987,
    ),
    Resort(
        slug="big-bear",
        name="Big Bear Mountain",
        state="CA",
        country="US",
        lat=34.2366,
        lon=-116.8910,
        base_elevation_m=2179,
        summit_elevation_m=2591,
    ),
    Resort(
        slug="sugar-bowl",
        name="Sugar Bowl",
        state="CA",
        country="US",
        lat=39.3047,
        lon=-120.3339,
        base_elevation_m=2042,
        summit_elevation_m=2530,
    ),
    # =========================================================================
    # WYOMING
    # =========================================================================
    Resort(
        slug="jackson-hole",
        name="Jackson Hole",
        state="WY",
        country="US",
        lat=43.5872,
        lon=-110.8281,
        base_elevation_m=1924,
        summit_elevation_m=3185,
    ),
    # =========================================================================
    # MONTANA
    # =========================================================================
    Resort(
        slug="big-sky",
        name="Big Sky",
        state="MT",
        country="US",
        lat=45.2862,
        lon=-111.4018,
        base_elevation_m=2072,
        summit_elevation_m=3403,
    ),
    # =========================================================================
    # IDAHO
    # =========================================================================
    Resort(
        slug="sun-valley",
        name="Sun Valley",
        state="ID",
        country="US",
        lat=43.6221,
        lon=-114.3511,
        base_elevation_m=1752,
        summit_elevation_m=2789,
    ),
    Resort(
        slug="schweitzer",
        name="Schweitzer",
        state="ID",
        country="US",
        lat=48.3678,
        lon=-116.6228,
        base_elevation_m=1220,
        summit_elevation_m=1920,
    ),
    # =========================================================================
    # NEW MEXICO
    # =========================================================================
    Resort(
        slug="taos",
        name="Taos Ski Valley",
        state="NM",
        country="US",
        lat=36.5958,
        lon=-105.4545,
        base_elevation_m=2804,
        summit_elevation_m=3804,
    ),
    # =========================================================================
    # OREGON
    # =========================================================================
    Resort(
        slug="mt-bachelor",
        name="Mt. Bachelor",
        state="OR",
        country="US",
        lat=43.9792,
        lon=-121.6886,
        base_elevation_m=1737,
        summit_elevation_m=2764,
    ),
    # =========================================================================
    # WASHINGTON
    # =========================================================================
    Resort(
        slug="crystal-mountain",
        name="Crystal Mountain",
        state="WA",
        country="US",
        lat=46.9282,
        lon=-121.5045,
        base_elevation_m=1341,
        summit_elevation_m=2134,
    ),
    Resort(
        slug="stevens-pass",
        name="Stevens Pass",
        state="WA",
        country="US",
        lat=47.7448,
        lon=-121.0890,
        base_elevation_m=1238,
        summit_elevation_m=1783,
    ),
    Resort(
        slug="snoqualmie",
        name="The Summit at Snoqualmie",
        state="WA",
        country="US",
        lat=47.4206,
        lon=-121.4137,
        base_elevation_m=923,
        summit_elevation_m=1655,
    ),
    # =========================================================================
    # VERMONT
    # =========================================================================
    Resort(
        slug="stowe",
        name="Stowe",
        state="VT",
        country="US",
        lat=44.5303,
        lon=-72.7814,
        base_elevation_m=390,
        summit_elevation_m=1339,
    ),
    Resort(
        slug="killington",
        name="Killington",
        state="VT",
        country="US",
        lat=43.6045,
        lon=-72.8201,
        base_elevation_m=335,
        summit_elevation_m=1293,
    ),
    Resort(
        slug="sugarbush",
        name="Sugarbush",
        state="VT",
        country="US",
        lat=44.1358,
        lon=-72.9053,
        base_elevation_m=427,
        summit_elevation_m=1244,
    ),
    Resort(
        slug="stratton",
        name="Stratton",
        state="VT",
        country="US",
        lat=43.1134,
        lon=-72.9081,
        base_elevation_m=579,
        summit_elevation_m=1180,
    ),
    Resort(
        slug="mount-snow",
        name="Mount Snow",
        state="VT",
        country="US",
        lat=42.9601,
        lon=-72.9204,
        base_elevation_m=549,
        summit_elevation_m=1094,
    ),
    Resort(
        slug="okemo",
        name="Okemo",
        state="VT",
        country="US",
        lat=43.4017,
        lon=-72.7170,
        base_elevation_m=343,
        summit_elevation_m=975,
    ),
    Resort(
        slug="jay-peak",
        name="Jay Peak",
        state="VT",
        country="US",
        lat=44.9267,
        lon=-72.5047,
        base_elevation_m=549,
        summit_elevation_m=1175,
    ),
    Resort(
        slug="smugglers-notch",
        name="Smugglers' Notch",
        state="VT",
        country="US",
        lat=44.5878,
        lon=-72.7861,
        base_elevation_m=314,
        summit_elevation_m=1103,
    ),
    # =========================================================================
    # NEW HAMPSHIRE
    # =========================================================================
    Resort(
        slug="loon-mountain",
        name="Loon Mountain",
        state="NH",
        country="US",
        lat=44.0364,
        lon=-71.6217,
        base_elevation_m=299,
        summit_elevation_m=945,
    ),
    Resort(
        slug="cannon-mountain",
        name="Cannon Mountain",
        state="NH",
        country="US",
        lat=44.1567,
        lon=-71.7006,
        base_elevation_m=579,
        summit_elevation_m=1270,
    ),
    Resort(
        slug="wildcat-mountain",
        name="Wildcat Mountain",
        state="NH",
        country="US",
        lat=44.2637,
        lon=-71.2394,
        base_elevation_m=600,
        summit_elevation_m=1309,
    ),
    Resort(
        slug="attitash",
        name="Attitash",
        state="NH",
        country="US",
        lat=44.0833,
        lon=-71.2292,
        base_elevation_m=183,
        summit_elevation_m=869,
    ),
    Resort(
        slug="bretton-woods",
        name="Bretton Woods",
        state="NH",
        country="US",
        lat=44.2583,
        lon=-71.4636,
        base_elevation_m=457,
        summit_elevation_m=945,
    ),
    Resort(
        slug="sunapee",
        name="Mount Sunapee",
        state="NH",
        country="US",
        lat=43.3294,
        lon=-72.0786,
        base_elevation_m=366,
        summit_elevation_m=823,
    ),
    # =========================================================================
    # MAINE
    # =========================================================================
    Resort(
        slug="sunday-river",
        name="Sunday River",
        state="ME",
        country="US",
        lat=44.4736,
        lon=-70.8567,
        base_elevation_m=244,
        summit_elevation_m=955,
    ),
    Resort(
        slug="sugarloaf",
        name="Sugarloaf",
        state="ME",
        country="US",
        lat=45.0314,
        lon=-70.3131,
        base_elevation_m=366,
        summit_elevation_m=1293,
    ),
    # =========================================================================
    # NEW YORK
    # =========================================================================
    Resort(
        slug="hunter-mountain",
        name="Hunter Mountain",
        state="NY",
        country="US",
        lat=42.2017,
        lon=-74.2258,
        base_elevation_m=488,
        summit_elevation_m=1006,
    ),
    Resort(
        slug="windham",
        name="Windham Mountain",
        state="NY",
        country="US",
        lat=42.2972,
        lon=-74.2569,
        base_elevation_m=457,
        summit_elevation_m=1006,
    ),
    Resort(
        slug="gore-mountain",
        name="Gore Mountain",
        state="NY",
        country="US",
        lat=43.6736,
        lon=-74.0039,
        base_elevation_m=610,
        summit_elevation_m=1098,
    ),
    Resort(
        slug="whiteface",
        name="Whiteface Mountain",
        state="NY",
        country="US",
        lat=44.3656,
        lon=-73.9033,
        base_elevation_m=373,
        summit_elevation_m=1483,
    ),
    # =========================================================================
    # WEST VIRGINIA
    # =========================================================================
    Resort(
        slug="snowshoe",
        name="Snowshoe",
        state="WV",
        country="US",
        lat=38.4150,
        lon=-79.9942,
        base_elevation_m=1311,
        summit_elevation_m=1476,
    ),
    # =========================================================================
    # MICHIGAN
    # =========================================================================
    Resort(
        slug="boyne-highlands",
        name="Boyne Highlands",
        state="MI",
        country="US",
        lat=45.4742,
        lon=-84.9372,
        base_elevation_m=213,
        summit_elevation_m=491,
    ),
    Resort(
        slug="boyne-mountain",
        name="Boyne Mountain",
        state="MI",
        country="US",
        lat=45.1517,
        lon=-84.9131,
        base_elevation_m=274,
        summit_elevation_m=500,
    ),
    # =========================================================================
    # BRITISH COLUMBIA, CANADA
    # =========================================================================
    Resort(
        slug="whistler-blackcomb",
        name="Whistler Blackcomb",
        state="BC",
        country="CA",
        lat=50.1163,
        lon=-122.9574,
        base_elevation_m=675,
        summit_elevation_m=2284,
    ),
    Resort(
        slug="revelstoke",
        name="Revelstoke",
        state="BC",
        country="CA",
        lat=51.0447,
        lon=-118.1636,
        base_elevation_m=512,
        summit_elevation_m=2225,
    ),
    Resort(
        slug="red-mountain",
        name="Red Mountain",
        state="BC",
        country="CA",
        lat=49.1044,
        lon=-117.8461,
        base_elevation_m=1185,
        summit_elevation_m=2075,
    ),
    Resort(
        slug="sun-peaks",
        name="Sun Peaks",
        state="BC",
        country="CA",
        lat=50.8833,
        lon=-119.9000,
        base_elevation_m=1255,
        summit_elevation_m=2152,
    ),
    Resort(
        slug="fernie",
        name="Fernie Alpine Resort",
        state="BC",
        country="CA",
        lat=49.4625,
        lon=-115.0872,
        base_elevation_m=1068,
        summit_elevation_m=2134,
    ),
    Resort(
        slug="kicking-horse",
        name="Kicking Horse",
        state="BC",
        country="CA",
        lat=51.2975,
        lon=-117.0475,
        base_elevation_m=1190,
        summit_elevation_m=2450,
    ),
    Resort(
        slug="cypress-mountain",
        name="Cypress Mountain",
        state="BC",
        country="CA",
        lat=49.3963,
        lon=-123.2046,
        base_elevation_m=898,
        summit_elevation_m=1440,
    ),
    # =========================================================================
    # ALBERTA, CANADA
    # =========================================================================
    Resort(
        slug="lake-louise",
        name="Lake Louise",
        state="AB",
        country="CA",
        lat=51.4254,
        lon=-116.1522,
        base_elevation_m=1646,
        summit_elevation_m=2637,
    ),
    Resort(
        slug="sunshine-village",
        name="Banff Sunshine Village",
        state="AB",
        country="CA",
        lat=51.0750,
        lon=-115.7636,
        base_elevation_m=1660,
        summit_elevation_m=2730,
    ),
    Resort(
        slug="mt-norquay",
        name="Mt. Norquay",
        state="AB",
        country="CA",
        lat=51.2028,
        lon=-115.6033,
        base_elevation_m=1630,
        summit_elevation_m=2133,
    ),
    Resort(
        slug="nakiska",
        name="Nakiska",
        state="AB",
        country="CA",
        lat=50.9422,
        lon=-115.1506,
        base_elevation_m=1525,
        summit_elevation_m=2258,
    ),
    Resort(
        slug="castle-mountain",
        name="Castle Mountain",
        state="AB",
        country="CA",
        lat=49.3125,
        lon=-114.4097,
        base_elevation_m=1410,
        summit_elevation_m=2270,
    ),
    Resort(
        slug="marmot-basin",
        name="Marmot Basin",
        state="AB",
        country="CA",
        lat=52.7992,
        lon=-118.0811,
        base_elevation_m=1698,
        summit_elevation_m=2612,
    ),
    # =========================================================================
    # QUEBEC, CANADA
    # =========================================================================
    Resort(
        slug="tremblant",
        name="Mont Tremblant",
        state="QC",
        country="CA",
        lat=46.2094,
        lon=-74.5869,
        base_elevation_m=265,
        summit_elevation_m=875,
    ),
    # =========================================================================
    # ONTARIO, CANADA
    # =========================================================================
    Resort(
        slug="blue-mountain",
        name="Blue Mountain",
        state="ON",
        country="CA",
        lat=44.5019,
        lon=-80.3156,
        base_elevation_m=218,
        summit_elevation_m=452,
    ),
]


def get_resort_by_slug(slug: str) -> Resort | None:
    """Find a resort by its slug."""
    for resort in RESORTS:
        if resort.slug == slug:
            return resort
    return None


def get_resorts_by_state(state: str) -> list[Resort]:
    """Get all resorts in a state/province."""
    return [r for r in RESORTS if r.state.upper() == state.upper()]
