"""Curated ski resort database."""

from app.models import Resort

# Curated list of popular ski resorts
RESORTS: list[Resort] = [
    Resort(
        slug="jackson-hole",
        name="Jackson Hole",
        state="WY",
        country="US",
        lat=43.5872,
        lon=-110.8281,
        base_elevation_m=1924,
        summit_elevation_m=3185,
    ),
    Resort(
        slug="alta",
        name="Alta",
        state="UT",
        country="US",
        lat=40.5884,
        lon=-111.6387,
        base_elevation_m=2600,
        summit_elevation_m=3216,
    ),
    Resort(
        slug="snowbird",
        name="Snowbird",
        state="UT",
        country="US",
        lat=40.5830,
        lon=-111.6538,
        base_elevation_m=2365,
        summit_elevation_m=3353,
    ),
    Resort(
        slug="mammoth-mountain",
        name="Mammoth Mountain",
        state="CA",
        country="US",
        lat=37.6308,
        lon=-119.0326,
        base_elevation_m=2424,
        summit_elevation_m=3369,
    ),
    Resort(
        slug="vail",
        name="Vail",
        state="CO",
        country="US",
        lat=39.6403,
        lon=-106.3742,
        base_elevation_m=2476,
        summit_elevation_m=3527,
    ),
    Resort(
        slug="palisades-tahoe",
        name="Palisades Tahoe",
        state="CA",
        country="US",
        lat=39.1969,
        lon=-120.2358,
        base_elevation_m=1890,
        summit_elevation_m=2760,
    ),
    Resort(
        slug="park-city",
        name="Park City",
        state="UT",
        country="US",
        lat=40.6514,
        lon=-111.5080,
        base_elevation_m=2103,
        summit_elevation_m=3048,
    ),
    Resort(
        slug="aspen-mountain",
        name="Aspen Mountain",
        state="CO",
        country="US",
        lat=39.1875,
        lon=-106.8186,
        base_elevation_m=2422,
        summit_elevation_m=3418,
    ),
    Resort(
        slug="big-sky",
        name="Big Sky",
        state="MT",
        country="US",
        lat=45.2862,
        lon=-111.4018,
        base_elevation_m=2072,
        summit_elevation_m=3403,
    ),
    Resort(
        slug="telluride",
        name="Telluride",
        state="CO",
        country="US",
        lat=37.9375,
        lon=-107.8123,
        base_elevation_m=2659,
        summit_elevation_m=4010,
    ),
    Resort(
        slug="whistler-blackcomb",
        name="Whistler Blackcomb",
        state="BC",
        country="CA",
        lat=50.1163,
        lon=-122.9574,
        base_elevation_m=675,
        summit_elevation_m=2284,
    ),
    Resort(
        slug="breckenridge",
        name="Breckenridge",
        state="CO",
        country="US",
        lat=39.4817,
        lon=-106.0384,
        base_elevation_m=2926,
        summit_elevation_m=3914,
    ),
    Resort(
        slug="steamboat",
        name="Steamboat",
        state="CO",
        country="US",
        lat=40.4572,
        lon=-106.8045,
        base_elevation_m=2103,
        summit_elevation_m=3221,
    ),
    Resort(
        slug="taos",
        name="Taos Ski Valley",
        state="NM",
        country="US",
        lat=36.5958,
        lon=-105.4545,
        base_elevation_m=2804,
        summit_elevation_m=3804,
    ),
    Resort(
        slug="kirkwood",
        name="Kirkwood",
        state="CA",
        country="US",
        lat=38.6850,
        lon=-120.0653,
        base_elevation_m=2377,
        summit_elevation_m=2987,
    ),
    Resort(
        slug="mt-bachelor",
        name="Mt. Bachelor",
        state="OR",
        country="US",
        lat=43.9792,
        lon=-121.6886,
        base_elevation_m=1737,
        summit_elevation_m=2764,
    ),
    Resort(
        slug="crystal-mountain",
        name="Crystal Mountain",
        state="WA",
        country="US",
        lat=46.9282,
        lon=-121.5045,
        base_elevation_m=1341,
        summit_elevation_m=2134,
    ),
    Resort(
        slug="sun-valley",
        name="Sun Valley",
        state="ID",
        country="US",
        lat=43.6221,
        lon=-114.3511,
        base_elevation_m=1752,
        summit_elevation_m=2789,
    ),
    Resort(
        slug="heavenly",
        name="Heavenly",
        state="CA",
        country="US",
        lat=38.9353,
        lon=-119.9400,
        base_elevation_m=1995,
        summit_elevation_m=3060,
    ),
    Resort(
        slug="deer-valley",
        name="Deer Valley",
        state="UT",
        country="US",
        lat=40.6375,
        lon=-111.4783,
        base_elevation_m=2003,
        summit_elevation_m=2917,
    ),
]


def get_resort_by_slug(slug: str) -> Resort | None:
    """Find a resort by its slug."""
    for resort in RESORTS:
        if resort.slug == slug:
            return resort
    return None


def get_resorts_by_state(state: str) -> list[Resort]:
    """Get all resorts in a state/province."""
    return [r for r in RESORTS if r.state.upper() == state.upper()]

